In [29]:
#Se define las librerias a utilizar
from sklearn.svm import SVC
from sklearn.decomposition import PCA
import pandas as pd #procesamiento de archi9vos 
import numpy as np
import matplotlib.pyplot as plt
import mglearn
from keras.models import Sequential
from keras.layers import Dense
from sklearn.linear_model import LogisticRegression
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix  #matrix de confusion
from sklearn import preprocessing
from keras import optimizers
from sklearn.metrics import classification_report
from sklearn.preprocessing import minmax_scale

In [30]:
def leerData(ruta):
    df = pd.read_csv(ruta, sep=',')
    return df

def dibujar(errorRate,title):
    plt.figure(figsize=(15, 6))
    plt.plot(errorRate, color='blue', linestyle='dashed',
             marker='o', markerfacecolor='red', markersize=10)
    plt.xlabel('Número de K')
    plt.ylabel(title)
    plt.show()
    return

def clasificadorSVM(kernel, X,y):
    cls=SVC(kernel=kernel,gamma=10)
    cls.fit(X,y)
    cls.score(X,y)
    return cls

def resultadosSVM(cls, X, y):
    score = cls.score(X, y)
    return score

def predecirSVM(cls, X, y):
    yPred = cls.predict(X)
    matrixConf = confusion_matrix(y, yPred)
    report = classification_report(y, yPred)
    return matrixConf, report
def NormalizarData(dataframe):
    #Columna 2
    dataframe = dataframe.replace('?',0)
    dataframe = dataframe.replace('State-gov',1)
    dataframe = dataframe.replace('Self-emp-not-inc',2)
    dataframe = dataframe.replace('Self-emp-inc',3)
    dataframe = dataframe.replace('Private',4)
    dataframe = dataframe.replace('Federal-gov',5)
    dataframe = dataframe.replace('Local-gov',6)    
    dataframe = dataframe.replace('Without-pay',7)
    dataframe = dataframe.replace('Never-worked',8)
    #Columa 4
    dataframe = dataframe.replace('Preschool',1)
    dataframe = dataframe.replace('1st-4th',2)
    dataframe = dataframe.replace('5th-6th',3)
    dataframe = dataframe.replace('7th-8th',4)
    dataframe = dataframe.replace('9th',5)
    dataframe = dataframe.replace('10th',6)
    dataframe = dataframe.replace('11th',7)
    dataframe = dataframe.replace('12th',8)
    dataframe = dataframe.replace('HS-grad',9)
    dataframe = dataframe.replace('Assoc-acdm',10)
    dataframe = dataframe.replace('Some-college',11)
    dataframe = dataframe.replace('Prof-school',12)    
    dataframe = dataframe.replace('Bachelors',13)
    dataframe = dataframe.replace('Masters',14)
    dataframe = dataframe.replace('Doctorate',15)    
    dataframe = dataframe.replace('Assoc-voc',16)
    #columna 6
    dataframe = dataframe.replace('Never-married',1)
    dataframe = dataframe.replace('Married-civ-spouse',2)
    dataframe = dataframe.replace('Widowed',3)
    dataframe = dataframe.replace('Not-in-family',4)
    dataframe = dataframe.replace('Separated',5)
    dataframe = dataframe.replace('Divorced',6)
    dataframe = dataframe.replace('Married-spouse-absent',7)
    dataframe = dataframe.replace('Married-AF-spouse',8)
    #columna 7
    dataframe = dataframe.replace('Machine-op-inspct',1)
    dataframe = dataframe.replace('Farming-fishing',2)
    dataframe = dataframe.replace('Protective-serv',3)
    dataframe = dataframe.replace('Machine-op-inspct',4)    
    dataframe = dataframe.replace('Other-service',5)
    dataframe = dataframe.replace('Prof-specialty',6)
    dataframe = dataframe.replace('Craft-repair',7)
    dataframe = dataframe.replace('Adm-clerical',8)
    dataframe = dataframe.replace('Exec-managerial',9)
    dataframe = dataframe.replace('Tech-support',10)
    dataframe = dataframe.replace('Craft-repair',11)
    dataframe = dataframe.replace('Sales',12)
    dataframe = dataframe.replace('Priv-house-serv',13)
    dataframe = dataframe.replace('Handlers-cleaners',14)
    dataframe = dataframe.replace('Transport-moving',15)
    dataframe = dataframe.replace('Armed-Forces',16)
    #columna 8
    dataframe = dataframe.replace('Own-child',1)
    dataframe = dataframe.replace('Husband',2)
    dataframe = dataframe.replace('Not-in-family',3)
    dataframe = dataframe.replace('Unmarried',4)
    dataframe = dataframe.replace('Wife',5)
    dataframe = dataframe.replace('Other-relative',6)
    #columna 9
    dataframe = dataframe.replace('Black',1)
    dataframe = dataframe.replace('White',2)
    dataframe = dataframe.replace('Asian-Pac-Islander',3)
    dataframe = dataframe.replace('Amer-Indian-Eskimo',4)
    dataframe = dataframe.replace('Other',5)
    #columna 10    
    dataframe = dataframe.replace('Male',1)
    dataframe = dataframe.replace('Female',2)
    #columna 11
    dataframe = dataframe.replace('United-States',1)    
    dataframe = dataframe.replace('Peru',2)
    dataframe = dataframe.replace('Guatemala',3)
    dataframe = dataframe.replace('Mexico',4)
    dataframe = dataframe.replace('Dominican-Republic',5)
    dataframe = dataframe.replace('Ireland',6)
    dataframe = dataframe.replace('Germany',7)
    dataframe = dataframe.replace('Philippines',8)
    dataframe = dataframe.replace('Thailand',9)
    dataframe = dataframe.replace('Haiti',10)
    dataframe = dataframe.replace('El-Salvador',11)
    dataframe = dataframe.replace('Puerto-Rico',12)
    dataframe = dataframe.replace('Vietnam',13)
    dataframe = dataframe.replace('South',14)
    dataframe = dataframe.replace('Columbia',15)
    dataframe = dataframe.replace('Japan',16)
    dataframe = dataframe.replace('India',17)
    dataframe = dataframe.replace('Cambodia',18)
    dataframe = dataframe.replace('Poland',19)
    dataframe = dataframe.replace('Laos',20)
    dataframe = dataframe.replace('England',21)
    dataframe = dataframe.replace('Cuba',22)
    dataframe = dataframe.replace('Taiwan',23)
    dataframe = dataframe.replace('Italy',24)
    dataframe = dataframe.replace('Canada',25)
    dataframe = dataframe.replace('Portugal',26)
    dataframe = dataframe.replace('China',27)
    dataframe = dataframe.replace('Nicaragua',28)
    dataframe = dataframe.replace('Honduras',29)
    dataframe = dataframe.replace('Iran',30)
    dataframe = dataframe.replace('Scotland',31)
    dataframe = dataframe.replace('Jamaica',32)
    dataframe = dataframe.replace('Ecuador',33)
    dataframe = dataframe.replace('Yugoslavia',34)
    dataframe = dataframe.replace('Hungary',35)
    dataframe = dataframe.replace('Hong',36)
    dataframe = dataframe.replace('Greece',37)
    dataframe = dataframe.replace('Trinadad&Tobago',38)
    dataframe = dataframe.replace('Outlying-US(Guam-USVI-etc)',39)
    dataframe = dataframe.replace('France',40)
    dataframe = dataframe.replace('Holand-Netherlands',40)
    #Columna     
    dataframe = dataframe.replace('<=50K',0)
    dataframe = dataframe.replace('>50K',1)
    dataframe = dataframe.replace('<=50K.',0)
    dataframe = dataframe.replace('>50K.',1)
    
    return dataframe

In [31]:
#Se lee los datos de entrenamiento y testeo
dataframe=leerData('adult-training.csv')
dataframe=NormalizarData(dataframe)
X_train = dataframe.values[:,:-1]
X_train = minmax_scale(X_train)
y_train= dataframe['income']
#print(dataframe)
dataframe=leerData('adult-test.csv')
dataframe=NormalizarData(dataframe)
X_test = dataframe.values[:,:-1]
X_test = minmax_scale(X_test)
y_test= dataframe['income']
#print(dataframe)


In [32]:
## Se concatena los datos de X_train y X_test para enviar al clasificador 
x=np.concatenate((X_train,X_test), axis=0)
y=np.concatenate((y_train,y_test), axis=0)

In [33]:
## Se ejecuta el clafificador para generar el modelo
cls=clasificadorSVM("poly",x,y)

In [34]:
##Se obtiene y se imprime medidas de Rendimiento
score_Train=resultadosSVM(cls,X_train,y_train)
print(round(score_Train,4))
score_Test=resultadosSVM(cls,X_test,y_test)
print(round(score_Test,4))


0.8529
0.8533


In [35]:
##Seobtiene y se imprime la matrices de confusion
matrix_conf, report =predecirSVM(cls,X_train,y_train)
print(matrix_conf)
print(report)
matrix_conf, report =predecirSVM(cls,X_test,y_test)
print(matrix_conf)
print(report)

[[23470  1250]
 [ 3541  4300]]
              precision    recall  f1-score   support

           0       0.87      0.95      0.91     24720
           1       0.77      0.55      0.64      7841

    accuracy                           0.85     32561
   macro avg       0.82      0.75      0.77     32561
weighted avg       0.85      0.85      0.84     32561

[[11791   644]
 [ 1744  2102]]
              precision    recall  f1-score   support

           0       0.87      0.95      0.91     12435
           1       0.77      0.55      0.64      3846

    accuracy                           0.85     16281
   macro avg       0.82      0.75      0.77     16281
weighted avg       0.85      0.85      0.84     16281



In [37]:
valPredict_train=cls.predict(X_train).round()
confusion_matrix_train=confusion_matrix(y_train,valPredict_train)
valPredict_test=cls.predict(X_test).round()
confusion_matrix_test=confusion_matrix(y_test,valPredict_test)

In [38]:
print("===============confusion_matrix_train===============")
print(confusion_matrix_train)
print("==============confusion_matrix_test================")
print(confusion_matrix_test)

===============confusion_matrix_train===============
[[23470  1250]
 [ 3541  4300]]
==============confusion_matrix_test================
[[11791   644]
 [ 1744  2102]]


In [39]:
print("CONCLUSIONES:")
print("Los resultados de la evaluacion del modelo son:")
print("-Entrenamiento: ",round(score_Train,4))
print("-Testeo: ",round(score_Test,4))

CONCLUSIONES:
Los resultados de la evaluacion del modelo son:
-Entrenamiento:  0.8529
-Testeo:  0.8533
